from model.keypoint_classifier.keypoint_classifier import KeyPointClassifier_R
from model.keypoint_classifier.keypoint_classifier import KeyPointClassifier_L
#from model.mouse_classifier.mouse_classifier import MouseClassifier
from model.dynamic_gestures_classifier.dynamic_gestures_classifier import DynamicGesturesClassifier

