# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camLabel = QtWidgets.QLabel(self.centralwidget)
        self.camLabel.setGeometry(QtCore.QRect(20, 100, 401, 420))
        self.camLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.camLabel.setObjectName("camLabel")
        self.openCamPushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.openCamPushbutton.setGeometry(QtCore.QRect(50, 60, 93, 28))
        self.openCamPushbutton.setObjectName("openCamPushbutton")
        self.closeCamPushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.closeCamPushbutton.setGeometry(QtCore.QRect(540, 60, 93, 28))
        self.closeCamPushbutton.setObjectName("closeCamPushbutton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 60, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.sysName = QtWidgets.QLabel(self.centralwidget)
        self.sysName.setGeometry(QtCore.QRect(140, 10, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.sysName.setFont(font)
        self.sysName.setObjectName("sysName")
        self.fpsLabel = QtWidgets.QLabel(self.centralwidget)
        self.fpsLabel.setGeometry(QtCore.QRect(580, 240, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fpsLabel.setFont(font)
        self.fpsLabel.setObjectName("fpsLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 290, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.handLabel = QtWidgets.QLabel(self.centralwidget)
        self.handLabel.setGeometry(QtCore.QRect(590, 290, 71, 31))
        self.handLabel.setObjectName("handLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 340, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.handLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.handLabel_2.setGeometry(QtCore.QRect(590, 340, 71, 31))
        self.handLabel_2.setObjectName("handLabel_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 390, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(610, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.xLabel = QtWidgets.QLabel(self.centralwidget)
        self.xLabel.setGeometry(QtCore.QRect(510, 450, 71, 31))
        self.xLabel.setObjectName("xLabel")
        self.yLabel = QtWidgets.QLabel(self.centralwidget)
        self.yLabel.setGeometry(QtCore.QRect(650, 450, 71, 31))
        self.yLabel.setObjectName("yLabel")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 110, 171, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 185, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 185, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.modeLabel = QtWidgets.QLabel(self.centralwidget)
        self.modeLabel.setGeometry(QtCore.QRect(450, 160, 311, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.modeLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.modeLabel.setFont(font)
        self.modeLabel.setObjectName("modeLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.camLabel.setText(_translate("MainWindow", "TextLabel"))
        self.openCamPushbutton.setText(_translate("MainWindow", "打开相机"))
        self.closeCamPushbutton.setText(_translate("MainWindow", "关闭相机"))
        self.comboBox.setItemText(0, _translate("MainWindow", "本地相机"))
        self.comboBox.setItemText(1, _translate("MainWindow", "外置相机"))
        self.sysName.setText(_translate("MainWindow", "基于手势检测的课堂教学辅助系统"))
        self.fpsLabel.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "FPS"))
        self.label_2.setText(_translate("MainWindow", "静态手势"))
        self.handLabel.setText(_translate("MainWindow", "None"))
        self.label_3.setText(_translate("MainWindow", "动态手势"))
        self.handLabel_2.setText(_translate("MainWindow", "None"))
        self.label_4.setText(_translate("MainWindow", "鼠标指针位置"))
        self.label_5.setText(_translate("MainWindow", "X"))
        self.label_6.setText(_translate("MainWindow", "Y"))
        self.xLabel.setText(_translate("MainWindow", "0"))
        self.yLabel.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "系统模式："))
        self.modeLabel.setText(_translate("MainWindow", "PPT播放控制模式"))
